// Generated by CoffeeScript 2.7.0
d3.json("salaries.json").then(function (salaries) {
  return d3.json("titles.json").then(function (titles) {
    return d3.json("divisions.json").then(function (divisions) {
      var dropdown, jobcodes, opts, results, title, x;
      dropdown = d3.select("body").select("select#division");
      opts = dropdown.selectAll("option").data(divisions).enter().append("option").text(function (d) {
        return d;
      }).attr("value", function (d) {
        return d;
      });
      // insert title into salaries dataset
      salaries.forEach(function (d) {
        return d.title = titles[d.JobCode];
      });
      // create object that has title -> job codes
      jobcodes = {};
      results = [];
      for (x in titles) {
        title = titles[x];
        if (!(jobcodes[title] != null)) {
          jobcodes[title] = [];
        }
        results.push(jobcodes[title].push(x));
      }
      return results;
    });
  });
});